#!/bin/sh
##
## curl https://raw.githubusercontent.com/ryanpcmcquen/config-o-matic/master/NEARFREE | sh

read -p "Would you like to become NEARFREE? \
(follows freeslack.net, but keeps kernel, not valid with most of the other options) \
[y/N]: " response
case $response in
  [yY][eE][sS]|[yY])
    export NEARFREE=true;
    echo You are becoming NEARFREE.;
    ;;
  *)
    echo You are not becoming NEARFREE.;
    ;;
esac

if [ "$NEARFREE" = true ]; then
  removepkg getty-ps lha unarj amp \
    bluez-firmware ipw2100-fw ipw2200-fw trn \
    zd1211-firmware xfractint xgames xv

  slackpkg blacklist getty-ps lha unarj amp \
    bluez-firmware ipw2100-fw ipw2200-fw trn \
    zd1211-firmware xfractint xgames xv

  echo "You have become NEARFREE, to update your kernel, head to freeslack.net."
fi

