#!/bin/sh

#  cd; wget -N https://raw.githubusercontent.com/ryanpcmcquen/config-o-matic/master/ryan -P ~/; sh ~/ryan; rm ~/ryan

## my ssh key
cd
if [ -z "$( ls ~/.ssh/ )" ]; then
  git clone https://ryanpcmcquen@bitbucket.org/ryanpcmcquen/.ssh.git
  chmod 700 .ssh/
  chmod 600 .ssh/*
  chmod 644 .ssh/id_rsa.pub
  chmod 644 .ssh/known_hosts
fi

## slackbuilds repo
git clone git@slackbuilds.org:slackbuilds.git sbo
cd sbo
git checkout -b user/ryan/updates
git checkout user/ryan/updates
git branch --set-upstream-to=origin/user/ryan/updates user/ryan/updates
git pull
cd


## sbo git hooks
wget -N https://raw.githubusercontent.com/ryanpcmcquen/linuxTweaks/master/slackware/sbo/hooks/commit-msg \
  -P ~/sbo/.git/hooks/
wget -N https://raw.githubusercontent.com/ryanpcmcquen/linuxTweaks/master/slackware/sbo/hooks/pre-commit \
  -P ~/sbo/.git/hooks/
  ## this is just in case permissions are incorrect,
  ## these files should already be 755  ;^)
  chmod 755 ~/sbo/.git/hooks/*


if [ ! -z "$( ls /usr/bin/asciinema )" ]; then
  asciinema auth
fi

