#!/bin/sh

#  cd; wget -N https://raw.githubusercontent.com/ryanpcmcquen/config-o-matic/master/ryan -P ~/; sh ~/ryan; rm ~/ryan

## run standard root script first
cd
wget -N https://raw.githubusercontent.com/ryanpcmcquen/config-o-matic/master/slackConfigROOT.sh
sh slackConfigROOT.sh
rm slackConfigROOT.sh

if [ ! $UID = 0 ]; then
  cat << EOF
This script must be run as root.
EOF
  exit 1
fi

## enable the wheel group
if [ ! -e /etc/sudoers.d/wheel-enable ]; then
  echo > /etc/sudoers.d/wheel-enable
  echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers.d/wheel-enable
  echo >> /etc/sudoers.d/wheel-enable
fi

## add all non-root users (except ftp) to wheel group
cat /etc/passwd | grep "/home" | cut -d: -f1 | sed '/ftp/d' | xargs -i usermod -G wheel -a {}
## the standard groups in case you forget when you run adduser  ;-)
cat /etc/passwd | grep "/home" | cut -d: -f1 | sed '/ftp/d' | \
  xargs -i usermod -G audio,cdrom,floppy,plugdev,video,power,netdev,lp,scanner -a {}


## my ssh key
cd
if [ ! -d ~/.ssh/ ]; then
  git clone https://ryanpcmcquen@bitbucket.org/ryanpcmcquen/.ssh.git
  chmod 700 .ssh/
  chmod 600 .ssh/*
  chmod 644 .ssh/id_rsa.pub
  chmod 644 .ssh/known_hosts
fi

## slackbuilds repo
git clone git@slackbuilds.org:slackbuilds.git sbo
cd sbo
git checkout -b user/ryan/updates
git checkout user/ryan/updates
git branch --set-upstream-to=origin/user/ryan/updates user/ryan/updates
git pull
cd


## sbo git hooks
wget -N https://raw.githubusercontent.com/ryanpcmcquen/linuxTweaks/master/slackware/sbo/hooks/commit-msg \
  -P ~/sbo/.git/hooks/
wget -N https://raw.githubusercontent.com/ryanpcmcquen/linuxTweaks/master/slackware/sbo/hooks/pre-commit \
  -P ~/sbo/.git/hooks/
## this is just in case permissions are incorrect,
## these files should already be 755  ;^)
chmod 755 ~/sbo/.git/hooks/*


if [ -e /usr/bin/asciinema ]; then
  asciinema auth
fi

echo "                    ..- - . "
echo "                   '        '. "
echo "                  '.- .  .--. . "
echo "                 |: _ | :  _ :| "
echo "                 |'(@)--'.(@) | "
echo "                 : .'     '-, : "
echo "                 :(_____.-'.' ' "
echo "                 : '-.__.-'   : "
echo "                 '  _.    _.   . "
echo "                /  /  '_ '  \    . "
echo "               .  :          \\   \ "
echo "              .  : _      __  .\   . "
echo "             .  /             : '.  \ "
echo "            :  /      '        : '.  . "
echo "           '  '      :          : :  '. "
echo "         .'_ :       :          / '   | "
echo "         :' \ .      :           '__  : "
echo "      .--'   \'-._    .      .' :    '). "
echo "    ..|       \   )          :   '._.'  : "
echo "   ;           \-'.        ..:         / "
echo "   '.           \  - ....-   |        ' "
echo "      -.         :   _____   |      .' "
echo "        ' -.    .'--       --'.   .' "
echo "            '--                -- "

